config/routes.rb
Rails.application.routes.draw do
  resources :posts do
    resources :comments
  end

  post '/users' => 'users#create'
  get "/signup" => "users#new"
  get "/signin" => "sessions#new"
  post "/signin" => "sessions#create"
  get "/signout" => "sessions#destroy"

  root 'pages#home', id: 'home'

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  # if you want to associate comments and posts to belong to a user, you would configure that here as well.
  belongs_to :post
end

app/models/post.rb
class Post < ActiveRecord::Base

  has_many :comments, dependent: :destroy
  validates :title, presence: true, length: {minimum: 5}
  validates :body, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
# here you can add associations so you can do things like:
#  user.posts, user.comments, etc..
  has_secure_password
  validates :email, presence: true, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  helper_method :current_user
  def current_user
    if session[:user_id]
      return User.find(session[:user_id])
    else
      return nil
    end
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  # :+1:
  def create
    @post = Post.find(params[:post_id])
    @comment = @post.comments.create(params[:comment].permit(:name, :body))

    redirect_to post_path(@post)

  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
# looks good overall
# I encourage you to look into how you can utilize your user model to authorize the ability edit/destroy posts.
# As it stands now, any user can edit or destroy anything. It would be nice if they couldn't
# and only the user that creates the post can edit/destroy it.

  def index
    # :+1: for ordering! noice
    @posts = Post.all.order('created_at DESC')
  end

  def new
    @post = Post.new
  end

  def show
    @post = Post.find(params[:id])
  end

  def create
    @post = Post.new(post_params)
    @comment = @post.comments.build
    if @post.save
      flash[:success] = "New post added!"
      redirect_to @post
    else
      render :new
    end
  end

  def edit
    @post = Post.find(params[:id])
  end

  def update
    @post = Post.find(params[:id])

    if @post.update(params[:post].permit(:title, :body))
      flash[:success] = "Your post has been updated!"
        redirect_to @post
      else
        render 'edit'
      end
    end

  def destroy
    @post= Post.find(params[:id])

    @post.destroy
    flash[:success] = "Your post was successfully deleted."
    redirect_to posts_path
  end

  private
  def post_params
    params.require(:post).permit(:username, :title, :body)
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(email: params[:signin][:email])
    if user
      if user.authenticate(params[:signin][:password])
        session[:user_id] = user.id
        flash[:success] = "Logged in as #{user.email}"
        redirect_to posts_path
      else
        render :new
        return
      end
    else
      render :new
      return
    end
  end

  def destroy
    session[:user_id] = nil

    flash[:success] = "You have signed out!"
    redirect_to root_path

  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      flash[:success] = "Signed Up Successfully!"
      redirect_to posts_path
    else
      render :new
    end
  end

  private
  def user_params
    params.require(:user).permit(:email, :password, :password_confirmation)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/pages_controller_helper.rb
module PagesControllerHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/comments/_form.html.erb
<%= simple_form_for ([@post, @post.comments.build])  do |f| %>

  <% if @post.errors.any? %>
      <div id='error-messages'>
        <% @user.errors.full_messages.each do |msg| %>
        <p>msg</p>
        <% end %>
      </div>
  <% end %>

  <%= f.input :username, placeholder: 'username', :input_html => {:style => 'width: 300px'} %>
  <%= f.input :body, placeholder: 'comment', :input_html => {:style => 'width: 300px'}, :input_html => {:rows => 7} %>
  <%= f.button :submit %>
<% end %>


<!-- <button type="submit" class="btn btn-default btn-sm">Submit</button> -->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <!-- theres a bit of code here thats not properly indented. -->
  <title>SimplyMommy</title>
   <link href='https://fonts.googleapis.com/css?family=Raleway:400,500|Poiret+One|Yesteryear' rel='stylesheet' type='text/css'>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <header class="navbar navbar-fixed-top navbar-inverse">
    <div class="container">
      <%= link_to "SimplyMommy", root_path, id: "logo" %>
      <nav>
        <ul class="nav navbar-nav navbar-right">
          <li><%= link_to "Home", root_path, {style: "color: #fff"} %></li>
          <li><%= link_to "Posts", posts_path, {style: "color: #fff"}%></li>

          <% if current_user %>
          Logged as: <%= current_user.email %>
          <li><%= link_to "Log Out", signout_path, {style: "color: #fff"}%></li>
          <% else %>
          <li><%= link_to "Log In", signin_path, {style: "color: #fff"}%></li>
          <% end %>
        </ul>
      </nav>
    </div>
  </header>


  <div class="container">
    <% flash.each do |name, msg| -%>
      <%= content_tag :div, msg, class: "alert alert-#{name}" %>
    <% end %>

    <%= yield %>
</div>

</body>
</html>

app/views/pages/home.html.erb
<header id="heading">
  <div class="center">
    <h1>SimplyMommy</h1>
    <h2>Where moms go for the simple answers to life's challenges.</h2>

    <%= link_to "Sign up!", signup_path, :class =>"btn.outline btn-lg btn-primary" %>
  </div>
</header>

app/views/posts/_form.html.erb
<!-- how'd you like simple form? I never used it, but have heard good things! -->
<%= simple_form_for @post  do |f| %>

  <% if @post.errors.any? %>
    <div id='error-messages'>
      <% @user.errors.full_messages.each do |msg| %>
        <p><%= msg %></p>
      <% end %>
    </div>
  <% end %>

  <%= f.input :username, placeholder: 'username', :input_html => {:style => 'width: 300px'} %>
  <%= f.input :title, :input_html => {:style => 'width: 300px'} %>
  <%= f.input :body, :input_html => {:style => 'width: 300px'}, :input_html => {:rows => 7} %>
  <%= f.button :submit %>
<% end %>

app/views/posts/edit.html.erb
<div class="all_wrapper">
  <div id="page_wrapper">
    <h4>Edit Post</h4>

    <%= render 'form' %>
  </div>
</div>

app/views/posts/index.html.erb
<div class="all_wrapper">
  <div class= "new_post">
    <h4><%= link_to "Add a Post", new_post_path %></h4>
  </div>

  <h1>Latest Posts</h1>
  <% @posts.each do |post| %>

  <div class = "post_wrapper">
    <h2 class= "title"><%= link_to post.title, post %></h2>
    <p class="date">Posted on: <%= post.created_at.strftime("%B %e, %Y  %l:%M%p") %></p>

  </div>

  <% end %>
</div>

app/views/posts/new.html.erb
<div class="all_wrapper">
  <div id="page_wrapper">
    <h3> New Post</h3>

    <%= render 'form' %>

  </div>
</div>

app/views/posts/show.html.erb
<div class="all_wrapper">
  <div id="post_container">
      <%= link_to 'Edit', edit_post_path(@post) %> |
  	  <%= link_to 'Delete', post_path(@post),
                method: :delete,
                data: { confirm: 'Are you sure?' } %>

    <h1 class="title"><%= @post.title %></h1>
    <p class="date">
      Posted on: <%= @post.created_at.strftime("%B %e, %Y  %l:%M%p") %>
    </p>
    <h3 class="body"><%= @post.body %></h3>

    <div id="comments_container">
      <p><%= @post.comments.count %> Comments</p>


      <% @post.comments.each do |comment| %>
        <p class="comment_username"><strong><%= comment.username %></strong>   posted on: <%= comment.created_at.strftime("%B %e, %Y  %l:%M%p") %></p>
        <p class="comment_body"><%= comment.body %></p>
      <% end %>

        <div class="add_comment_container"
          <h4>Add a comment:</h4>
          <%= render 'comments/form' %>
        </div>
    </div>
  </div>
</div>

app/views/users/new.html.erb
<h2>Sign up!</h2>


<%= simple_form_for @user  do |f| %>

  <% if @user.errors.any? %>
    <div id='error-messages'>
      <% @user.errors.full_messages.each do |msg| %>
      <p><%= msg %></p>
      <% end %>
    </div>
  <% end %>

  <%= f.input :email, placeholder: 'user@domain.com', :input_html => {:style => 'width: 300px'} %>
  <%= f.input :password, placeholder: 'password', :input_html => {:style => 'width: 300px'} %>
  <%= f.input :password_confirmation, placeholder: 'password confirmation', :input_html => {:style => 'width: 300px'} %>
  <%= f.button :submit %>
<% end %>